import Head from "next/head";
import clsx from "clsx";
import { Rubik } from "next/font/google";

const font = Rubik({
  subsets: ["latin", "latin-ext"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={clsx(font.className, "flex min-h-screen flex-col ")}>
        <nav className="flex items-center bg-[#f1f1f1] px-20 py-2">
          <div className="text-xl font-semibold">Parent App</div>
        </nav>
        <div className="grid grow place-items-center px-20">
          <div className="w-full overflow-hidden rounded border">
            <iframe
              src="http://localhost:3001"
              sandbox="allow-same-origin allow-scripts allow-popups allow-forms"
              className="h-[75dvh] w-full"
            ></iframe>
          </div>
        </div>
      </main>
    </>
  );
}
